# Generated by Django 3.0.2 on 2021-04-01 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poster', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extimestamp', models.DateTimeField(default=datetime.datetime(2021, 4, 2, 19, 15, 3, 129783, tzinfo=utc))),
                ('status', models.BooleanField(default=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('topics', models.ManyToManyField(to='piazza.Topic')),
            ],
        ),
    ]
