# Generated by Django 3.0.2 on 2021-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('poster', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('extimestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('likes', models.PositiveIntegerField()),
                ('dislikes', models.PositiveIntegerField()),
            ],
        ),
    ]
