# Generated by Django 3.0.2 on 2021-03-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0002_auto_20210330_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
