# Generated by Django 3.0.2 on 2021-04-06 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0005_auto_20210405_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='extimestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 11, 35, 27, 662074, tzinfo=utc)),
        ),
    ]
