# Generated by Django 3.0.2 on 2021-04-06 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0007_auto_20210406_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('action', models.CharField(max_length=60)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timeLeft', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='extimestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 14, 38, 22, 828318, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='postActions',
            field=models.ManyToManyField(to='piazza.PostAction'),
        ),
    ]
