# Generated by Django 3.0.2 on 2021-04-06 22:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0013_auto_20210406_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='extimestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 22, 53, 14, 578799, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postaction',
            name='timeLeft',
            field=models.DateTimeField(),
        ),
    ]
