# Generated by Django 3.0.2 on 2021-04-06 23:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('piazza', '0015_auto_20210406_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaction',
            name='timeLeftMinutes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='extimestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 23, 1, 0, 308763, tzinfo=utc)),
        ),
    ]
